import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { DatabaseSync } from "node:sqlite";
import test from "node:test";

const files = ["0009_zukan_foundation_v2_source_identity.sql", "0010_zukan_foundation_v2_predicate_claims.sql", "0011_zukan_foundation_v2_authority_resolution.sql", "0012_zukan_foundation_v2_governance_rights.sql", "0013_zukan_foundation_v2_disputes_coverage.sql"];
function db(): DatabaseSync { const d = new DatabaseSync(":memory:"); d.exec("PRAGMA foreign_keys=ON"); for (const f of files) d.exec(readFileSync(new URL(`../../cloudflare_shadow/migrations/core/${f}`, import.meta.url), "utf8")); return d; }
function one(d: DatabaseSync, sql: string, ...p: Array<string | number>): unknown { const r = d.prepare(sql).get(...p) as Record<string, unknown> | undefined; return r && Object.values(r)[0]; }
function core(d: DatabaseSync): void {
  d.exec(`INSERT INTO zukan_subject_identities(subject_id,tenant_id,subject_kind) VALUES ('shop-a','t','place'),('shop-b','t','place'),('owner','t','agent'),('taxon','t','taxon');
    INSERT INTO zukan_predicate_definitions(predicate_uri,predicate_version,value_type,cardinality,polarity_mode,temporal_profile) VALUES ('https://zukan.earth/p/hours',1,'string','one','positive_or_negative','valid_time');`);
}
function claims(d: DatabaseSync): number {
  core(d); d.exec(`INSERT INTO zukan_claims(claim_id,subject_id,predicate_uri,predicate_version,tenant_id) VALUES ('city','shop-a','https://zukan.earth/p/hours',1,'t'),('owner-c','shop-a','https://zukan.earth/p/hours',1,'t'),('later','shop-a','https://zukan.earth/p/hours',1,'t');
    INSERT INTO zukan_value_artifacts(artifact_id,value_text) VALUES ('a-city','09-17'),('a-owner','10-18'),('a-later','24h');
    INSERT INTO zukan_claim_revisions(claim_revision_id,claim_id,revision,predicate_uri,predicate_version,value_artifact_id,observed_at) VALUES ('r-city','city',1,'https://zukan.earth/p/hours',1,'a-city','2026-01-01'),('r-owner','owner-c',1,'https://zukan.earth/p/hours',1,'a-owner','2026-01-01');`);
  const mark = Number(one(d,"SELECT max(recorded_sequence) FROM zukan_claim_revisions"));
  d.exec(`INSERT INTO zukan_claim_revisions(claim_revision_id,claim_id,revision,predicate_uri,predicate_version,value_artifact_id,observed_at) VALUES ('r-later','later',1,'https://zukan.earth/p/hours',1,'a-later','2027-01-01');`); return mark;
}
function resolution(d: DatabaseSync, mark: number): void { d.prepare(`INSERT INTO zukan_resolution_policy_versions(resolution_policy_id,policy_key,policy_version,rules_json) VALUES ('policy-v1','hours',1,'{}')`).run(); d.prepare(`INSERT INTO zukan_resolution_runs(resolution_run_id,tenant_id,subject_id,predicate_uri,predicate_version,candidate_query_id,candidate_query_version,claim_store_snapshot_token,claim_store_sequence_watermark,recorded_time_watermark,predicate_registry_snapshot_hash,authority_snapshot_hash,resolution_policy_id,evaluator_build,input_hash,output_hash,run_status) VALUES ('run','t','shop-a','https://zukan.earth/p/hours',1,'q',1,?,?,'2026-12-31',?,?, 'policy-v1','build',?,?,'disputed')`).run(`seq:${mark}`,mark,"a".repeat(64),"b".repeat(64),"c".repeat(64),"d".repeat(64)); }

test("#16 identity split keeps old publication and returns ambiguity",()=>{const d=db();core(d);d.exec(`INSERT INTO zukan_public_identifiers VALUES ('pid','https://zukan.earth/id/old','subject_identity','shop-a','normal',CURRENT_TIMESTAMP,NULL); INSERT INTO zukan_identity_resolution_sets(resolution_set_id,valid_from,valid_to) VALUES ('old','2024','2027'),('split','2027',NULL); INSERT INTO zukan_identity_membership_assertions(membership_assertion_id,resolution_set_id,subject_id,membership_state,valid_from) VALUES ('ma','split','shop-a','candidate','2027'),('mb','split','shop-b','candidate','2027'); INSERT INTO zukan_canonical_identity_assertions(canonical_assertion_id,public_identifier_id,assertion_mode,resolution_set_id,valid_from) VALUES ('ca','pid','ambiguous','split','2027'); INSERT INTO zukan_canonical_identity_candidates VALUES ('ca','shop-a',0),('ca','shop-b',1);`);assert.equal(one(d,"SELECT assertion_mode FROM zukan_canonical_identity_assertions"),"ambiguous");assert.equal(one(d,"SELECT count(*) FROM zukan_canonical_identity_candidates"),2);d.close();});
test("#17 non-detection then detection is not unassessed",()=>{const d=db();core(d);d.exec(`INSERT INTO zukan_survey_events(survey_event_id,tenant_id,subject_scope_json,method_json,effort_json,started_at) VALUES ('s24','t','{}','{}','{}','2024'),('s26','t','{}','{}','{}','2026'); INSERT INTO zukan_detection_outcomes VALUES ('o24','s24','taxon','not_detected',NULL,CURRENT_TIMESTAMP),('o26','s26','taxon','detected',NULL,CURRENT_TIMESTAMP);`);assert.equal(one(d,"SELECT count(*) FROM zukan_detection_outcomes WHERE subject_id='taxon'"),2);assert.equal(one(d,"SELECT count(*) FROM zukan_claims"),0);d.close();});
test("#18 correction and publication suppression are separate events",()=>{const d=db();core(d);d.exec(`INSERT INTO zukan_correction_requests(correction_request_id,subject_id,request_payload_json) VALUES ('c','shop-a','{}'); INSERT INTO zukan_correction_request_events(correction_request_event_id,correction_request_id,event_type) VALUES ('ce','c','under_review'); INSERT INTO zukan_suppression_requests(suppression_request_id,target_kind,target_id,requested_action,request_reason) VALUES ('s','publication_edition','p','suppress','pending'); INSERT INTO zukan_suppression_request_events(suppression_request_event_id,suppression_request_id,event_type) VALUES ('se','s','approved');`);assert.equal(one(d,"SELECT event_type FROM zukan_correction_request_events"),"under_review");assert.equal(one(d,"SELECT event_type FROM zukan_suppression_request_events"),"approved");d.close();});
test("#19 destructive predicate mutation is rejected",()=>{const d=db();core(d);assert.throws(()=>d.exec("UPDATE zukan_predicate_definitions SET polarity_mode='positive_only'"),/immutable/);d.exec(`INSERT INTO zukan_predicate_definitions(predicate_uri,predicate_version,value_type,cardinality,polarity_mode,temporal_profile) VALUES ('https://zukan.earth/p/hours-v2',1,'string','one','positive_only','valid_time')`);d.close();});
test("#20 sequence watermark fixes the candidate set",()=>{const d=db();const mark=claims(d);resolution(d,mark);assert.equal(one(d,"SELECT count(*) FROM zukan_claim_revisions WHERE recorded_sequence<=?",mark),2);assert.equal(one(d,"SELECT count(*) FROM zukan_claim_revisions"),3);assert.throws(()=>d.exec("UPDATE zukan_resolution_runs SET claim_store_sequence_watermark=999"),/immutable/);d.close();});
test("#21 publication expiry does not remove preservation and embedding stays unknown",()=>{const d=db();d.exec(`INSERT INTO zukan_content_objects(content_object_id,object_kind) VALUES ('pdf','source_object'),('emb','embedding'); INSERT INTO zukan_rights_evaluations(rights_evaluation_id,content_object_id,purpose,basis,valid_from,valid_to) VALUES ('pub','pdf','publication','allowed','2025','2027'),('pres','pdf','preservation','allowed','2025',NULL),('em','emb','embedding','unknown','2025',NULL);`);assert.equal(one(d,"SELECT basis FROM zukan_rights_evaluations WHERE rights_evaluation_id='pres'"),"allowed");assert.equal(one(d,"SELECT basis FROM zukan_rights_evaluations WHERE rights_evaluation_id='em'"),"unknown");d.close();});
test("#22 erase tombstones value and records degraded replay",()=>{const d=db();const mark=claims(d);resolution(d,mark);d.exec(`INSERT INTO zukan_projection_snapshots(projection_snapshot_id,resolution_run_id,snapshot_hash,reproducibility_at_issue,issued_at) VALUES ('snap','run','${"e".repeat(64)}','full','2027'); INSERT INTO zukan_projection_entries VALUES ('snap','hours','r-city','a-city','{}'); UPDATE zukan_value_artifacts SET value_text=NULL,content_sha256=NULL,storage_locator=NULL,availability_status='erased',redacted_at='2027' WHERE artifact_id='a-city'; INSERT INTO zukan_content_governance_events(governance_event_id,action,target_kind,target_id,reason,effective_at) VALUES ('erase','erase','value_artifact','a-city','legal','2027'); INSERT INTO zukan_snapshot_status_events(snapshot_status_event_id,projection_snapshot_id,governance_event_id,reproducibility_status,affected_entry_keys_json) VALUES ('status','snap','erase','degraded','["hours"]');`);assert.equal(one(d,"SELECT snapshot_hash FROM zukan_projection_snapshots"),"e".repeat(64));assert.equal(one(d,"SELECT availability_status FROM zukan_value_artifacts WHERE artifact_id='a-city'"),"erased");assert.equal(one(d,"SELECT reproducibility_status FROM zukan_snapshot_status_events"),"degraded");d.close();});
test("#23 authority revocation is append-only and mode explicit",()=>{const d=db();core(d);d.exec(`INSERT INTO zukan_trust_anchors(trust_anchor_id,tenant_id,anchor_method,external_reference,assurance_level,valid_from,policy_version) VALUES ('ta','t','authenticated_account','owner',90,'2025','v1'); INSERT INTO zukan_authority_assertions(authority_assertion_id,authority_subject_id,trust_anchor_id,authority_rank,valid_from) VALUES ('auth','owner','ta',100,'2025'); INSERT INTO zukan_authority_revocation_events(revocation_event_id,authority_assertion_id,revocation_mode,effective_at,reason) VALUES ('pro','auth','prospective','2027','ended'),('retro','auth','retroactive','2028','impersonation');`);assert.equal(one(d,"SELECT count(*) FROM zukan_authority_assertions"),1);assert.equal(one(d,"SELECT count(*) FROM zukan_authority_revocation_events"),2);assert.throws(()=>d.exec("UPDATE zukan_authority_revocation_events SET revocation_mode='retroactive' WHERE revocation_event_id='pro'"),/immutable/);d.close();});
test("#24 equal authority contradiction opens dispute with no accepted claim",()=>{const d=db();const mark=claims(d);resolution(d,mark);d.exec(`INSERT INTO zukan_resolution_run_claims VALUES ('run','r-city','candidate','equal_authority',100,0),('run','r-owner','candidate','equal_authority',100,1); INSERT INTO zukan_dispute_cases(dispute_case_id,subject_id,predicate_uri,predicate_version,resolution_run_id) VALUES ('dispute','shop-a','https://zukan.earth/p/hours',1,'run'); INSERT INTO zukan_dispute_case_events(dispute_case_event_id,dispute_case_id,event_type) VALUES ('open','dispute','opened');`);assert.equal(one(d,"SELECT count(*) FROM zukan_resolution_run_claims WHERE decision='accepted'"),0);assert.equal(one(d,"SELECT event_type FROM zukan_dispute_case_events"),"opened");d.close();});
