#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"

export DATABASE_URL="${DATABASE_URL:-postgresql:///ikimon_v2_staging?host=%2Fvar%2Frun%2Fpostgresql}"
export V2_BASE_URL="${V2_BASE_URL:-http://127.0.0.1:3200}"
export CUTOVER_FIXTURE_PREFIX="${CUTOVER_FIXTURE_PREFIX:-staging-cutover-rehearsal}"
export CUTOVER_LEGACY_MIRROR_ROOT="${CUTOVER_LEGACY_MIRROR_ROOT:-}"
export CUTOVER_FALLBACK_LEGACY_MIRROR_ROOT="${CUTOVER_FALLBACK_LEGACY_MIRROR_ROOT:-}"
export CUTOVER_FALLBACK_LEGACY_DATA_ROOT="${CUTOVER_FALLBACK_LEGACY_DATA_ROOT:-}"
export CUTOVER_LEGACY_DATA_ROOT="${CUTOVER_LEGACY_DATA_ROOT:-}"
export CUTOVER_UPLOADS_ROOT="${CUTOVER_UPLOADS_ROOT:-}"
export CUTOVER_PUBLIC_ROOT="${CUTOVER_PUBLIC_ROOT:-}"
export CUTOVER_PREPARE_VERIFY_FIXTURE="${CUTOVER_PREPARE_VERIFY_FIXTURE:-0}"
export CUTOVER_VERIFY_FIXTURE_OUTPUT_ROOT="${CUTOVER_VERIFY_FIXTURE_OUTPUT_ROOT:-}"
export CUTOVER_VERIFY_IMPORT_VERSION="${CUTOVER_VERIFY_IMPORT_VERSION:-}"

if [[ "$(id -un)" == "root" ]]; then
  exec sudo -u postgres env \
    DATABASE_URL="${DATABASE_URL}" \
    V2_BASE_URL="${V2_BASE_URL}" \
    CUTOVER_FIXTURE_PREFIX="${CUTOVER_FIXTURE_PREFIX}" \
    CUTOVER_LEGACY_MIRROR_ROOT="${CUTOVER_LEGACY_MIRROR_ROOT}" \
    CUTOVER_FALLBACK_LEGACY_MIRROR_ROOT="${CUTOVER_FALLBACK_LEGACY_MIRROR_ROOT}" \
    CUTOVER_FALLBACK_LEGACY_DATA_ROOT="${CUTOVER_FALLBACK_LEGACY_DATA_ROOT}" \
    CUTOVER_LEGACY_DATA_ROOT="${CUTOVER_LEGACY_DATA_ROOT}" \
    CUTOVER_UPLOADS_ROOT="${CUTOVER_UPLOADS_ROOT}" \
    CUTOVER_PUBLIC_ROOT="${CUTOVER_PUBLIC_ROOT}" \
    CUTOVER_PREPARE_VERIFY_FIXTURE="${CUTOVER_PREPARE_VERIFY_FIXTURE}" \
    CUTOVER_VERIFY_FIXTURE_OUTPUT_ROOT="${CUTOVER_VERIFY_FIXTURE_OUTPUT_ROOT}" \
    CUTOVER_VERIFY_IMPORT_VERSION="${CUTOVER_VERIFY_IMPORT_VERSION}" \
    CUTOVER_FORCE_SYNC="${CUTOVER_FORCE_SYNC:-0}" \
    CUTOVER_SKIP_READ_SMOKE="${CUTOVER_SKIP_READ_SMOKE:-0}" \
    CUTOVER_SKIP_WRITE_SMOKE="${CUTOVER_SKIP_WRITE_SMOKE:-0}" \
    bash "${BASH_SOURCE[0]}"
fi

cd "${PROJECT_ROOT}"

ARGS=(
  "--base-url=${V2_BASE_URL}"
  "--fixture-prefix=${CUTOVER_FIXTURE_PREFIX}"
)

if [[ "${CUTOVER_PREPARE_VERIFY_FIXTURE}" == "1" && -n "${CUTOVER_LEGACY_MIRROR_ROOT}" && -z "${CUTOVER_LEGACY_DATA_ROOT}" ]]; then
  VERIFY_FIXTURE_OUTPUT_ROOT="${CUTOVER_VERIFY_FIXTURE_OUTPUT_ROOT:-${CUTOVER_LEGACY_MIRROR_ROOT}/verify-fixtures/latest}"
  MATERIALIZE_ARGS=("--mirror-root=${CUTOVER_LEGACY_MIRROR_ROOT}")
  if [[ -n "${CUTOVER_FALLBACK_LEGACY_MIRROR_ROOT}" ]]; then
    MATERIALIZE_ARGS+=("--fallback-mirror-root=${CUTOVER_FALLBACK_LEGACY_MIRROR_ROOT}")
  fi
  if [[ -n "${CUTOVER_FALLBACK_LEGACY_DATA_ROOT}" ]]; then
    MATERIALIZE_ARGS+=("--fallback-legacy-data-root=${CUTOVER_FALLBACK_LEGACY_DATA_ROOT}")
  fi
  MATERIALIZE_ARGS+=("--output-root=${VERIFY_FIXTURE_OUTPUT_ROOT}")
  if [[ -n "${CUTOVER_VERIFY_IMPORT_VERSION}" ]]; then
    MATERIALIZE_ARGS+=("--import-version=${CUTOVER_VERIFY_IMPORT_VERSION}")
  fi
  npm run materialize:legacy-verify-snapshot -- "${MATERIALIZE_ARGS[@]}"
  ARGS+=("--legacy-data-root=${VERIFY_FIXTURE_OUTPUT_ROOT}/data")
fi

if [[ -n "${CUTOVER_LEGACY_DATA_ROOT}" ]]; then
  ARGS+=("--legacy-data-root=${CUTOVER_LEGACY_DATA_ROOT}")
fi
if [[ -n "${CUTOVER_LEGACY_MIRROR_ROOT}" ]]; then
  ARGS+=("--mirror-root=${CUTOVER_LEGACY_MIRROR_ROOT}")
fi
if [[ -n "${CUTOVER_UPLOADS_ROOT}" ]]; then
  ARGS+=("--uploads-root=${CUTOVER_UPLOADS_ROOT}")
fi
if [[ -n "${CUTOVER_PUBLIC_ROOT}" ]]; then
  ARGS+=("--public-root=${CUTOVER_PUBLIC_ROOT}")
fi
if [[ "${CUTOVER_FORCE_SYNC:-0}" == "1" ]]; then
  ARGS+=("--force-sync")
fi
if [[ "${CUTOVER_SKIP_READ_SMOKE:-0}" == "1" ]]; then
  ARGS+=("--skip-read-smoke")
fi
if [[ "${CUTOVER_SKIP_WRITE_SMOKE:-0}" == "1" ]]; then
  ARGS+=("--skip-write-smoke")
fi

npm run rehearse:cutover -- "${ARGS[@]}"
