import assert from "node:assert/strict";
import test from "node:test";

import { GUIDE_FLOW_STYLES, renderGuideFlow } from "./guideFlow.js";

test("guide flow exposes a photo fallback when camera access is unavailable", () => {
  const html = renderGuideFlow("", "ja");

  assert.match(html, /id="guide-photo-fallback" hidden/);
  assert.match(html, /id="guide-photo-btn" type="button"/);
  assert.match(html, /id="guide-photo-input" type="file" accept="image\/\*" hidden/);
  assert.match(html, /記録用写真を選ぶ/);
  assert.match(html, /写真を解析中/);
  assert.match(html, /audioPrivacyPolicy: 'photo_fallback_no_audio'/);
});

test("guide live capture starts video-only and asks for microphone separately", () => {
  const html = renderGuideFlow("", "en");

  assert.match(html, /id="guide-start-sheet" hidden/);
  assert.match(html, /Use the camera\?/);
  assert.match(html, /Camera on/);
  assert.match(html, /Camera off/);
  assert.match(html, /Record audio too\?/);
  assert.match(html, /Audio on/);
  assert.match(html, /Audio off/);
  assert.match(html, /Today&#39;s mission/);
  assert.match(html, /Walk with screen/);
  assert.match(html, /Pocket audio/);
  assert.match(html, /Study one spot/);
  assert.match(html, /Bike \/ open car/);
  assert.match(html, /Car \/ train \/ bus/);
  assert.match(html, /Enclosed-vehicle preset applied/);
  assert.match(html, /mission === 'open_ride'/);
  assert.match(html, /applyMissionPreset\(input\.value \|\| 'quick'\)/);
  assert.match(html, /mission === 'drive'/);
  assert.match(html, /setSelectValue\('guide-mode-select', 'vehicle'\)/);
  assert.match(html, /setNextAction\(representative\.nextLookTarget \|\| copy\.nowNextFallback\)/);
  assert.match(html, /id="guide-now-next" hidden/);
  assert.match(html, /sessionInsights\(counts\)/);
  assert.match(html, /retryHintForAutoSave\(scene\)/);
  assert.match(html, /Audio connects each discovery to four shelves/);
  assert.match(html, /natural-sound candidates/);
  assert.match(html, /Similar clips become bundles or clusters/);
  assert.match(html, /AI suggestions stay provisional/);
  assert.match(html, /Recommended setup/);
  assert.match(html, /Use recommended/);
  assert.match(html, /Start with these settings/);
  assert.match(html, /let audioOptIn = false/);
  assert.match(html, /let cameraOptIn = true/);
  assert.match(html, /let audioOnlyChunkCount = 0/);
  assert.match(html, /const OFFLINE_DB_NAME = 'ikimon-guide-offline-v1'/);
  assert.match(html, /const OFFLINE_STORE = 'queue'/);
  assert.match(html, /mirrorAppOutboxItem\(item, 'queued'\)/);
  assert.match(html, /source: 'guide'/);
  assert.match(html, /removeAppOutboxItem\(item\.id\)/);
  assert.match(html, /window\.addEventListener\('online'/);
  assert.match(html, /window\.addEventListener\('ikimon-app-outbox-sync'/);
  assert.match(html, /window\.addEventListener\('offline'/);
  assert.match(html, /id="guide-offline-queued" hidden/);
  assert.match(html, /id="guide-summary-queued">0<\/strong>/);
  assert.match(html, /id="guide-audio-opt-btn" type="button" aria-pressed="false"/);
  assert.match(html, /Audio is saved only if you enable natural sound recording below\./);
  assert.match(html, /Field-like discoveries are saved automatically; indoor, person-first, or weak nature signals are not kept\./);
  assert.match(html, /autoSaveView\(scene\)/);
  assert.match(html, /const trailBundles = new Map\(\)/);
  assert.match(html, /function upsertTrailBundle\(scene\)/);
  assert.match(html, /scene-bundle-/);
  assert.match(html, /代表 ' \+ bundle\.scenes\.length \+ '件/);
  assert.match(GUIDE_FLOW_STYLES, /\.gdi-bundle/);
  assert.match(html, /copy\.autoSaved/);
  assert.match(html, /copy\.manualSave/);
  assert.match(html, /clientSceneId: payload\.clientSceneId/);
  assert.match(html, /externalId: newQueueId\('guide-audio'\)/);
  assert.match(html, /await queueScenePayload\(payload, 'offline'\)/);
  assert.match(html, /await queueAudioPayload\(payload, blob, 'offline'\)/);
  assert.match(html, /if \(vad\.speechLikely\)/);
  assert.match(html, /const AUDIO_CHUNK_TARGET_MS = 2000/);
  assert.match(html, /const AUDIO_CHUNK_MIN_MS = 1600/);
  assert.match(html, /const AUDIO_CHUNK_MAX_MS = 3200/);
  assert.match(html, /validateAudioChunkQuality\(blob, chunkMeta\)/);
  assert.match(html, /webm_header_missing/);
  assert.match(html, /hasWebmEbmlHeader\(header\)/);
  assert.match(html, /clientAudioQuality: quality/);
  assert.match(html, /sceneAudioChunks = \[blob\]/);
  assert.match(html, /let audioSliceTimer = null/);
  assert.match(html, /startStandaloneRecorderSlice/);
  assert.match(html, /recorder\.start\(\)/);
  assert.match(html, /AUDIO_CHUNK_TARGET_MS\)/);
  assert.match(html, /requestEnvironmentCamera\(\)/);
  assert.match(html, /facingMode: \{ exact: 'environment' \}/);
  assert.match(html, /navigator\.geolocation\.watchPosition/);
  assert.match(html, /function startLocationWatch\(\)/);
  assert.match(html, /locationAccuracyM: payload\.locationAccuracyM/);
  assert.match(html, /positionCapturedAt: payload\.positionCapturedAt/);
  assert.match(html, /sessionDistanceM: Math\.round\(sessionDistanceM\)/);
  assert.match(html, /audio: \{ channelCount: 1, echoCancellation: true, noiseSuppression: true, autoGainControl: false \}/);
  assert.match(html, /startBtn\.addEventListener\('click', openStartSheet\)/);
  assert.match(html, /recommendedApply\.addEventListener\('click', applyRecommendedSettings\)/);
  assert.match(html, /cameraOptIn = selectedChoice\('guide-camera-choice', 'on'\) === 'on'/);
  assert.match(html, /const TELEMETRY_INTERVAL_MS = 1500/);
  assert.match(html, /const VISUAL_SAMPLE_INTERVAL_MS = 5000/);
  assert.match(html, /const GUIDE_FRAME_BUNDLE_SIZE = 3/);
  assert.match(html, /const VISUAL_CANDIDATE_BUFFER_SIZE = 5/);
  assert.match(html, /const AI_MIN_INTERVAL_MS = 15000/);
  assert.match(html, /candidateCount >= GUIDE_FRAME_BUNDLE_SIZE/);
  assert.match(html, /candidateCount < GUIDE_FRAME_BUNDLE_SIZE/);
  assert.match(html, /const LOCAL_COVERAGE_CELL_M = 10/);
  assert.match(html, /function guideEffortSummary\(frameCount\)/);
  assert.match(html, /function guideCoverageSummary\(\)/);
  assert.match(html, /effortSummary: guideEffortSummary\(bundle \? bundle\.length : 1\)/);
  assert.match(html, /coverageSummary: guideCoverageSummary\(\)/);
  assert.match(html, /function startGuideSampling\(\)/);
  assert.match(html, /startGuideSampling\(\)/);
  assert.match(html, /\/api\/v1\/guide\/telemetry/);
  assert.match(html, /visualCandidates\.slice\(-GUIDE_FRAME_BUNDLE_SIZE\)/);
  assert.match(html, /frames: frames/);
  assert.match(html, /frameBundleSummary: payload\.frameBundleSummary/);
  assert.match(html, /effortSummary: payload\.effortSummary \|\| null/);
  assert.match(html, /coverageSummary: payload\.coverageSummary \|\| null/);
  assert.match(html, /function aiModelMeta\(scene\)/);
  assert.match(html, /visualExtractModel: scene\.visualExtractModel \|\| null/);
  assert.match(html, /textModel: scene\.textModel \|\| null/);
  assert.match(html, /gdi-ai-models/);
  assert.match(html, /audioMimeType: audioMimeType/);
  assert.match(html, /audioMimeType: item\.audioMimeType \|\| null/);
  assert.match(html, /id="guide-coverage"/);
  assert.match(html, /id="guide-coverage-map"/);
  assert.match(html, /guide-coverage-missing/);
  assert.match(html, /guide-coverage-visited/);
  assert.match(html, /maplibre-gl@4\.7\.1/);
  assert.match(html, /function targetCellFeatures\(field, feature\)/);
  assert.match(html, /const coverageSceneIds = new Set\(\)/);
  assert.match(html, /function applyReadySceneToCoverage\(scene\)/);
  assert.match(html, /applyReadySceneToCoverage\(scene\)/);
  const addPendingDiscovery = html.slice(
    html.indexOf("function addPendingDiscovery(scene)"),
    html.indexOf("function addQueuedDiscovery(scene)"),
  );
  assert.doesNotMatch(addPendingDiscovery, /\brepresentative\b/);
  assert.doesNotMatch(html, /const capturedAt = bundle \? framePayload\.capturedAt/);
  assert.match(html, /const capturedAt = new Date\(\)\.toISOString\(\);/);
  assert.match(html, /10mセル/);
  assert.doesNotMatch(html, /setTimeout\(doAnalyse, 5000\)/);
  assert.match(html, /stopLocationWatch\(\)/);
  assert.match(html, /showSessionSummary\(\)/);
  assert.match(GUIDE_FLOW_STYLES, /height: min\(68dvh, 640px\)/);
  assert.match(html, /if \(audioOptIn\) void startOptionalAudioCapture\(\);/);
  assert.doesNotMatch(html, /\n\s+void startOptionalAudioCapture\(\);\n\s+void prepareLiveAssist/);
  assert.doesNotMatch(html, /Camera & microphone access required/);
  assert.match(html, /Guide camera unavailable/);
});

test("guide start sheet explains Japanese camera and audio choices gently", () => {
  const html = renderGuideFlow("", "ja");

  assert.match(html, /使うものを選んで開始します/);
  assert.match(html, /今日のミッション/);
  assert.match(html, /徒歩で見ながら記録/);
  assert.match(html, /ポケット音声/);
  assert.match(html, /1地点を詳しく見る/);
  assert.match(html, /自転車・オープンカー/);
  assert.match(html, /車内・電車・バス/);
  assert.match(html, /カメラON \+ 音声OFF \+ 移動中モード/);
  assert.match(html, /おすすめ設定/);
  assert.match(html, /徒歩、自転車、オープンカー/);
  assert.match(html, /おすすめを使う/);
  assert.match(html, /ポケットに入れて使う日は/);
  assert.match(html, /ポケットに入れて音だけ集めるときはOFF/);
  assert.match(html, /外を歩いたり自転車で移動する場合/);
  assert.match(html, /人の声らしい音は保存しないよう除外します/);
  assert.match(html, /音声ONで、発見が4つの棚につながります/);
  assert.match(html, /自然音候補、似た音のまとまり、レビュー待ち、研究利用候補/);
  assert.match(html, /bundle \/ cluster/);
  assert.match(html, /BioMonWeek 型の観測データ/);
  assert.match(html, /音声だけで記録中/);
  assert.match(html, /カメラ映像は取得していません/);
  assert.match(html, /カメラか音声のどちらかをONにすると開始できます/);
  assert.match(html, /今回のふりかえり/);
  assert.match(html, /保存されたもの/);
  assert.match(html, /保存しなかったもの/);
  assert.match(html, /音声だけで取れたもの/);
  assert.match(html, /今日見えたもの/);
  assert.match(html, /足りない証拠/);
  assert.match(html, /次回見るもの/);
  assert.match(html, /ゆっくり1方向へ向けて/);
  assert.match(html, /人工物だけでなく、近くの草/);
  assert.match(html, /未同期のもの/);
  assert.match(html, /乗り物移動/);
  assert.match(html, /href="\/guide\/outcomes"/);
  assert.match(html, /ガイド成果を確認する/);
  assert.match(html, /オフライン中/);
  assert.match(html, /端末に一時保存中/);
  assert.match(html, /端末の保存容量に近づいています/);
});
