import { findPublicWorkOpportunities, workOpportunityKindLabel, type PublicWorkOpportunity, type WorkOpportunityQuery } from "../services/workOpportunity.js";
import { escapeHtml, renderSiteDocument } from "./siteShell.js";

export const WORK_OPPORTUNITY_STYLES = `.work-entry{max-width:1200px;margin:0 auto;padding:40px 28px 96px;color:#17211b}.work-entry h1{font-size:clamp(2rem,5vw,3rem);line-height:1.2;margin:0 0 12px}.work-lead{max-width:720px;color:#55615a;line-height:1.75}.work-search{display:grid;grid-template-columns:minmax(14rem,2fr) minmax(10rem,1fr) minmax(10rem,1fr) auto;gap:12px;margin:32px 0;padding:20px;background:#f7f7f3;border-radius:16px}.work-search label{display:grid;gap:6px;font-weight:700}.work-search input,.work-search select,.work-search button,.work-retry,.work-clear{min-height:44px;border:1px solid #98a39d;border-radius:8px;padding:9px 12px;font:inherit}.work-search button{align-self:end;background:#143f2e;color:#fff;border-color:#143f2e;font-weight:700}.work-results{display:grid;gap:16px}.work-card{border:1px solid #d9dedb;border-radius:14px;padding:22px;background:#fff}.work-card-kind{font-size:.85rem;color:#55615a}.work-card h2{font-size:1.35rem;margin:6px 0}.work-facts{display:flex;flex-wrap:wrap;gap:8px 18px;padding:0;list-style:none;color:#33443a}.work-summary{line-height:1.75}.work-evidence{border-top:1px solid #e2e5e3;margin-top:16px;padding-top:14px;color:#55615a;font-size:.875rem}.work-card a,.work-clear,.work-retry{color:#143f2e;font-weight:700;text-underline-offset:3px}.work-state{padding:28px;border:1px solid #d9dedb;border-radius:14px}.work-state h2{margin-top:0}@media(max-width:767px){.work-entry{padding:28px 20px 104px}.work-search{grid-template-columns:1fr}.work-card{padding:18px}}@media(max-width:374px){.work-entry{padding-inline:16px}.work-facts{display:grid;gap:6px}}`;
type Input={items:readonly PublicWorkOpportunity[];query:WorkOpportunityQuery;state:"ready"|"unavailable";currentPath:string};
const val=(value?:string)=>escapeHtml(value??"");

export function renderWorkOpportunityDiscoveryBody(input:Input):string {
 const cards=findPublicWorkOpportunities(input.items,input.query).map((item)=>`<article class="work-card"><span class="work-card-kind">${escapeHtml(workOpportunityKindLabel(item.kind))}</span><h2><a href="${escapeHtml(item.detailPath)}">${escapeHtml(item.title)}</a></h2><ul class="work-facts"><li><strong>職場</strong> ${escapeHtml(item.organizationName)}</li><li><strong>場所</strong> ${escapeHtml(item.placeName)}</li><li><strong>関わり方</strong> ${escapeHtml(item.relationshipLabel)}</li><li><strong>給与・報酬</strong> ${escapeHtml(item.payLabel??"給与・報酬は公開情報で確認できません")}</li>${item.scheduleLabel?`<li><strong>勤務・開催</strong> ${escapeHtml(item.scheduleLabel)}</li>`:""}</ul><p class="work-summary">${escapeHtml(item.summary)}</p><p class="work-evidence"><strong>情報源と更新日</strong><br><a href="${escapeHtml(item.sourceUrl)}" rel="noopener noreferrer">${escapeHtml(item.sourceLabel)}</a> / <time datetime="${escapeHtml(item.publishedAt)}">${escapeHtml(item.publishedAt.slice(0,10))}</time></p></article>`).join("");
 const state=input.state==="unavailable"?`<section class="work-state" role="status"><h2>仕事の情報を読み込めませんでした</h2><p>通信状態を確かめてください。</p><a class="work-retry" href="${escapeHtml(input.currentPath)}">もう一度読み込む</a></section>`:cards||`<section class="work-state"><h2>条件に合う仕事・職場・見学は見つかりませんでした</h2><p>キーワードや場所を変えるか、条件をクリアしてください。</p><a class="work-clear" href="/ja/jobs">条件をクリア</a></section>`;
 return `<main class="work-entry" id="main-content"><p class="work-card-kind">地域の参加・仕事</p><h1>仕事・職場・見学を探す</h1><p class="work-lead">募集条件だけでなく、働く場所、関わり方、情報源と更新日を一緒に確かめられます。</p><form class="work-search" action="/ja/jobs" method="get" role="search"><label>キーワード<input name="q" type="search" value="${val(input.query.query)}" placeholder="仕事・職場・団体名" enterkeyhint="search"></label><label>場所<input name="place" value="${val(input.query.place)}" placeholder="市区町村・地域"></label><label>種類<select name="kind"><option value="all">すべて</option><option value="job"${input.query.kind==="job"?" selected":""}>仕事</option><option value="workplace"${input.query.kind==="workplace"?" selected":""}>職場</option><option value="visit"${input.query.kind==="visit"?" selected":""}>見学・仕事体験</option></select></label><button type="submit">探す</button></form><section aria-labelledby="work-results-title"><h2 id="work-results-title">公開されている情報</h2><div class="work-results">${state}</div></section></main>`;
}
export function renderWorkOpportunityDiscovery(input:Input):string { return renderSiteDocument({basePath:"",lang:"ja",title:"仕事・職場・見学を探す | ZUKAN",description:"地域の仕事、職場、見学を公開情報と更新日から探します。",currentPath:input.currentPath,canonicalPath:"/jobs",body:renderWorkOpportunityDiscoveryBody(input),extraStyles:WORK_OPPORTUNITY_STYLES,activeNav:"community"}); }
