import { escapeHtml } from "../../src/ui/siteShell";
import type { SavedItem } from "./savedItems";
export type QuietHomeLang = "ja" | "en" | "es" | "pt-br";
export const quietHomeCopy = {
  ja:{title:"見つける",search:"公開された記録を探す",searchHint:"名前・場所・キーワード",submit:"探す",places:"場所から探す",events:"参加できること",records:"みんなの記録",saved:"保存したもの",all:"すべて見る",mine:"自分の記録",recordUnavailable:"記録を読み込めませんでした。",none:"気になるものを保存すると、ここから見返せます。",unavailable:"保存したものを読み込めませんでした。",retry:"もう一度読み込む",save:"保存",savedButton:"保存済み",remove:"保存を解除",saving:"保存しています…",removing:"解除しています…",savedStatus:"ZUKANに保存しました。自分だけに見えます。",removedStatus:"保存を解除しました。",error:"変更を確認できませんでした。もう一度お試しください。",conflict:"保存状態が変わりました。確認してもう一度お試しください。",privateNote:"自分だけの保存です。予約・応募・参加の申込みは行いません。",next:"次の保存を見る",end:"ここまでです。",record:"記録",place:"場所",event:"イベント",job:"求人",offer:"特典",article:"読みもの",organization:"団体・企業",experience:"体験",stay:"宿泊",learning:"学び",service:"サービス"},
  en:{title:"Discover",search:"Search public records",searchHint:"Name, place or keyword",submit:"Search",places:"Explore places",events:"Find activities",records:"Community records",saved:"Saved",all:"View all",mine:"Your records",recordUnavailable:"Your records could not be loaded.",none:"Save something of interest to find it here later.",unavailable:"Saved items could not be loaded.",retry:"Try again",save:"Save",savedButton:"Saved",remove:"Remove from saved",saving:"Saving…",removing:"Removing…",savedStatus:"Saved privately in ZUKAN.",removedStatus:"Removed from saved.",error:"The change could not be confirmed. Please try again.",conflict:"The saved state changed. Check it and try again.",privateNote:"Only you can see these saves. Saving does not book, apply or register.",next:"Next saved items",end:"You are up to date.",record:"Record",place:"Place",event:"Event",job:"Job",offer:"Offer",article:"Article",organization:"Organization",experience:"Experience",stay:"Stay",learning:"Learning",service:"Service"},
  es:{title:"Descubrir",search:"Buscar registros públicos",searchHint:"Nombre, lugar o palabra clave",submit:"Buscar",places:"Explorar lugares",events:"Encontrar actividades",records:"Registros de la comunidad",saved:"Guardados",all:"Ver todos",mine:"Tus registros",recordUnavailable:"No se pudieron cargar tus registros.",none:"Guarda algo que te interese para encontrarlo aquí.",unavailable:"No se pudieron cargar los elementos guardados.",retry:"Reintentar",save:"Guardar",savedButton:"Guardado",remove:"Quitar de guardados",saving:"Guardando…",removing:"Quitando…",savedStatus:"Guardado de forma privada en ZUKAN.",removedStatus:"Quitado de guardados.",error:"No se pudo confirmar el cambio. Inténtalo de nuevo.",conflict:"El estado cambió. Compruébalo e inténtalo de nuevo.",privateNote:"Solo tú puedes ver estos elementos. Guardar no reserva, solicita ni inscribe.",next:"Más elementos guardados",end:"Eso es todo.",record:"Registro",place:"Lugar",event:"Evento",job:"Empleo",offer:"Oferta",article:"Artículo",organization:"Organización",experience:"Experiencia",stay:"Alojamiento",learning:"Aprendizaje",service:"Servicio"},
  "pt-br":{title:"Descobrir",search:"Buscar registros públicos",searchHint:"Nome, lugar ou palavra-chave",submit:"Buscar",places:"Explorar lugares",events:"Encontrar atividades",records:"Registros da comunidade",saved:"Salvos",all:"Ver todos",mine:"Seus registros",recordUnavailable:"Não foi possível carregar seus registros.",none:"Salve algo interessante para encontrar aqui depois.",unavailable:"Não foi possível carregar os itens salvos.",retry:"Tentar novamente",save:"Salvar",savedButton:"Salvo",remove:"Remover dos salvos",saving:"Salvando…",removing:"Removendo…",savedStatus:"Salvo de forma privada no ZUKAN.",removedStatus:"Removido dos salvos.",error:"Não foi possível confirmar a alteração. Tente novamente.",conflict:"O estado mudou. Verifique e tente novamente.",privateNote:"Só você vê estes itens. Salvar não reserva, candidata nem inscreve.",next:"Próximos itens salvos",end:"Isso é tudo.",record:"Registro",place:"Lugar",event:"Evento",job:"Vaga",offer:"Oferta",article:"Artigo",organization:"Organização",experience:"Experiência",stay:"Hospedagem",learning:"Aprendizado",service:"Serviço"}
} as const;
export const QUIET_HOME_STYLES = `
.qh{box-sizing:border-box;width:100%;max-width:1120px;margin:24px auto 40px;padding:0 20px;color:#17211b;font-size:1rem;line-height:1.7;min-width:0}
.qh *{box-sizing:border-box}.qh h1{font-size:clamp(1.65rem,4vw,2rem);line-height:1.4;margin:0 0 24px;font-weight:700}.qh h2{font-size:1.375rem;line-height:1.45;margin:0}
.qh p{margin:8px 0 16px;color:#55615a}.qh a{color:#143f2e;text-underline-offset:4px}.qh :is(a,button,input):focus-visible,.zs-control:focus-visible{outline:3px solid currentColor;outline-offset:3px}
.qh-search label{display:block;margin-bottom:8px}.qh-search-row{display:flex;gap:8px}.qh-search input{min-width:0;flex:1;min-height:48px;border:1px solid #68746c;border-radius:4px;padding:10px 12px;font:inherit;color:inherit;background:#fff}
.qh-search button{min-height:48px;min-width:64px;padding:8px 16px;border:1px solid #143f2e;border-radius:4px;background:#143f2e;color:#fff;font:inherit;font-weight:700}
.qh-entrances{display:flex;flex-wrap:wrap;gap:8px 24px;margin:16px 0 32px}.qh-entrances a{display:inline-flex;align-items:center;min-height:44px;font-weight:700}
.qh-section{padding:24px 0;border-top:1px solid #dde2dc}.qh-heading{display:flex;justify-content:space-between;align-items:center;gap:16px;margin-bottom:12px}.qh-heading a{flex-shrink:0;display:inline-flex;align-items:center;min-height:44px}
.qh-list{display:grid;gap:0}.qh-item{display:flex;align-items:center;gap:16px;padding:16px 0;min-width:0;border-bottom:1px solid #dde2dc}.qh-item-link{flex:1;min-width:0;overflow-wrap:anywhere;text-decoration:none}.qh-item-link strong{display:block;font-weight:700}.qh-meta{display:block;font-size:.875rem;color:#55615a}
.zs-control{display:inline-flex;align-items:center;justify-content:center;gap:6px;min-width:72px;min-height:44px;border:1px solid #68746c;border-radius:4px;padding:8px 12px;background:#fff;color:#143f2e;font:inherit;line-height:1.4;cursor:pointer}.zs-control[aria-pressed=true]{border-color:#143f2e;background:#f7f7f3}.zs-control:disabled{cursor:wait}.zs-control svg{width:18px;height:18px;flex:none}.zs-card{min-width:0;display:grid;align-content:start;gap:8px}.zs-card>.zs-control{justify-self:end}.zs-status{font-size:.875rem;line-height:1.6;min-height:1.6em;color:#55615a}
.qh-recent-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px}.qh-recent-grid .home-recent-card{min-width:0;display:block;text-decoration:none}.qh-recent-grid .home-card-media{display:block;aspect-ratio:4/3;overflow:hidden;background:#f7f7f3;border-radius:8px}.qh-recent-grid img{width:100%;height:100%;object-fit:cover}.qh-recent-grid .home-card-copy{display:block;padding:8px 0;font-size:1rem}.qh-recent-grid .home-card-copy span{display:block;font-size:.875rem;color:#55615a}
.home-member-primary.is-quiet-recovery{padding:16px 20px;margin:16px auto;min-height:0;max-width:1120px;border:1px solid #dde2dc;background:#f7f7f3}.home-member-primary.is-quiet-recovery h2{font-size:1.125rem}.home-member-primary.is-quiet-recovery p{margin:8px 0}.home-member-primary.is-quiet-recovery .home-member-eyebrow{display:none}
.qh-footer{display:flex;align-items:center;gap:24px;flex-wrap:wrap;padding:16px 0}.qh-footer a{display:inline-flex;align-items:center;min-height:44px}
@media(max-width:600px){.qh{margin-top:16px;padding-inline:0}.qh-item{gap:12px}.qh-recent-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.qh-recent-grid>:nth-child(n+3){display:none}.qh-search button{padding-inline:12px}.qh-heading{gap:8px}}
`;
export function renderSavedControl(reference: Pick<SavedItem,"kind"|"objectId"|"path"|"title">, lang:QuietHomeLang, current:SavedItem|null=null) {
 const c=quietHomeCopy[lang];const saved=current?.state==="saved";
 return `<button type="button" class="zs-control" data-zukan-save data-saved-reference="${escapeHtml(JSON.stringify({kind:reference.kind,objectId:reference.objectId,path:reference.path,title:reference.title}))}" data-saved-revision="${current?.revision??0}" aria-pressed="${saved}" aria-label="${escapeHtml(`${saved?c.remove:c.save}: ${reference.title}`)}"><svg viewBox="0 0 24 24" aria-hidden="true" fill="${saved?'currentColor':'none'}" stroke="currentColor" stroke-width="1.7"><path d="M6 3h12v18l-6-4-6 4z"/></svg><span>${escapeHtml(saved?c.savedButton:c.save)}</span></button>`;
}
function savedRows(items:SavedItem[],lang:QuietHomeLang,controls:boolean) {
 const c=quietHomeCopy[lang]; return items.map(item=>`<article class="qh-item" data-saved-item-row><a class="qh-item-link" href="/${lang}${escapeHtml(item.path)}"><strong>${escapeHtml(item.title)}</strong><span class="qh-meta">${escapeHtml(c[item.kind])}</span></a>${controls?renderSavedControl(item,lang,item):""}</article>`).join("");
}
export function renderSavedPage(page:{items:SavedItem[];nextCursor:string|null}|null,lang:QuietHomeLang) {
 const c=quietHomeCopy[lang];
 return `<section class="qh" data-zukan-saved-page><style>${QUIET_HOME_STYLES}</style><h1>${c.saved}</h1><p>${c.privateNote}</p><p class="zs-status" data-zukan-saved-status aria-live="polite"></p>${page===null?`<p role="status">${c.unavailable}</p><a href="/${lang}/records?view=saved">${c.retry}</a>`:page.items.length?`<div class="qh-list">${savedRows(page.items,lang,true)}</div>${page.nextCursor?`<a href="/${lang}/records?view=saved&amp;cursor=${encodeURIComponent(page.nextCursor)}">${c.next}</a>`:`<p>${c.end}</p>`}`:`<p>${c.none}</p>`}<footer class="qh-footer"><a href="/${lang}/records?view=public">${c.records}</a><a href="/${lang}/records?view=mine">${c.mine}</a></footer>${renderSavedItemsScript(lang)}</section>`;
}
export function renderQuietHome(options:{lang:QuietHomeLang;saved:{items:SavedItem[]}|null;recentHtml:string;recordsUnavailable?:boolean}) {
 const {lang,saved,recentHtml}=options;const c=quietHomeCopy[lang];
 // Current runtime has records, places and participation. Future peer portals enter only after availability is proven.
 return `<section class="qh" data-zukan-quiet-home data-home-primary-state="explore" data-home-primary-active="true"><style>${QUIET_HOME_STYLES}</style><h1>${c.title}</h1><form class="qh-search" action="/${lang}/records" method="get" role="search"><input type="hidden" name="view" value="public"><label for="qh-query">${c.search}</label><div class="qh-search-row"><input id="qh-query" type="search" name="q" maxlength="80" placeholder="${c.searchHint}"><button type="submit">${c.submit}</button></div></form><nav class="qh-entrances" aria-label="${c.title}"><a href="/${lang}/map?tab=places">${c.places}</a><a href="/${lang}/community/events">${c.events}</a></nav><section class="qh-section"><div class="qh-heading"><h2>${c.saved}</h2><a href="/${lang}/records?view=saved">${c.all}</a></div>${saved===null?`<p>${c.unavailable}</p>`:saved.items.length?`<div class="qh-list">${savedRows(saved.items.slice(0,3),lang,false)}</div>`:`<p>${c.none}</p>`}</section>${recentHtml||options.recordsUnavailable?`<section class="qh-section"><div class="qh-heading"><h2>${c.mine}</h2><a href="/${lang}/records?view=mine">${c.all}</a></div>${options.recordsUnavailable?`<p role="status">${c.recordUnavailable}</p>`:`<div class="qh-recent-grid">${recentHtml}</div>`}</section>`:""}</section>`;
}
export function renderSavedItemsScript(lang:QuietHomeLang) {
 const c=JSON.stringify(quietHomeCopy[lang]).replace(/</g,"\\u003c");
 return `<script>(()=>{
 const copy=${c};const buttons=document.querySelectorAll('[data-zukan-save]');
 let status=document.querySelector('[data-zukan-saved-status]');
 if(!status&&buttons.length){status=document.createElement('p');status.className='zs-status';status.setAttribute('aria-live','polite');status.setAttribute('data-zukan-saved-status','');buttons[0].parentElement.parentElement.before(status);}
 const say=text=>{if(status)status.textContent=text;};
 const set=(button,item)=>{const saved=item?.state==='saved';button.dataset.savedRevision=String(item?.revision??0);button.setAttribute('aria-pressed',String(saved));button.querySelector('span').textContent=saved?copy.savedButton:copy.save;button.querySelector('svg').setAttribute('fill',saved?'currentColor':'none');const ref=JSON.parse(button.dataset.savedReference);button.setAttribute('aria-label',(saved?copy.remove:copy.save)+': '+ref.title);};
 buttons.forEach(button=>button.addEventListener('click',async()=>{
  if(button.disabled)return;button.disabled=true;
  const reference=JSON.parse(button.dataset.savedReference);const previous=button.getAttribute('aria-pressed')==='true';
  const command=button._savedPending??{reference,state:previous?'removed':'saved',expectedRevision:Number(button.dataset.savedRevision),commandId:crypto.randomUUID()};
  button._savedPending=command;button.querySelector('span').textContent=command.state==='saved'?copy.saving:copy.removing;
  try{
   const response=await fetch('/api/v1/me/saved',{method:'POST',credentials:'same-origin',headers:{'content-type':'application/json'},body:JSON.stringify(command)});
   if(response.status===409){const fresh=await fetch('/api/v1/me/saved?kind='+encodeURIComponent(reference.kind)+'&objectId='+encodeURIComponent(reference.objectId),{credentials:'same-origin'});if(!fresh.ok)throw Error('refresh');const current=await fresh.json();set(button,current.item);delete button._savedPending;say(copy.conflict);return;}
   if(!response.ok)throw Error('save');const result=await response.json();
   if(!result.item||result.item.kind!==reference.kind||result.item.objectId!==reference.objectId||result.item.state!==command.state)throw Error('receipt');
   set(button,result.item);delete button._savedPending;say(result.item.state==='saved'?copy.savedStatus:copy.removedStatus);
   if(result.item.state==='removed'&&button.closest('[data-zukan-saved-page]')){const row=button.closest('[data-saved-item-row]');const next=row.nextElementSibling?.querySelector('a')??row.previousElementSibling?.querySelector('a')??document.querySelector('.qh-footer a');row.remove();next?.focus();}
  }catch{button.querySelector('span').textContent=previous?copy.savedButton:copy.save;say(copy.error);}
  finally{button.disabled=false;}
 }));
})();</script>`;
}
