/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env=shadow --include-runtime=false --env-interface=ShadowGeneratedEnv src/worker-configuration.d.ts` (hash: 2957bb08fa6f2e63d1d091186af84909)
interface __BaseEnv_ShadowGeneratedEnv {
	ASSET_BUCKET: R2Bucket;
	CORE_DB: D1Database;
	OBS_DB: D1Database;
	ALERT_EMAIL: SendEmail;
	MEDIA_QUEUE: Queue;
	ALERT_QUEUE: Queue;
	AI: Ai;
	IMAGES: ImagesBinding;
	CF_VERSION_METADATA: WorkerVersionMetadata;
	ENVIRONMENT: "shadow";
	PUBLIC_LOCATION_CELL_PRECISION: "geohash6";
	OBSERVATION_DB_NAME: "ikimon_shadow_observations_2026_06";
	OBSERVATION_ARCHIVE_TARGET: "r2_sql_export_by_partition_month";
	OBSERVATION_DUAL_WRITE_MODE: "off";
	OBSERVATION_READ_CUTOVER_MODE: "off";
	ZUKAN_FOUNDATION_V2_SHADOW_READ_MODE: "off";
	ZUKAN_FOUNDATION_V2_DUAL_WRITE_MODE: "off";
	ZUKAN_FOUNDATION_V2_WRITE_KILL_SWITCH: "on";
	ZUKAN_FOUNDATION_V2_ALLOWED_TENANTS: "";
	ZUKAN_FOUNDATION_V2_ALLOWED_OPERATIONS: "";
	ZUKAN_FOUNDATION_V2_MAX_ENTITIES: "64";
	ALERT_EMAIL_FROM: "notifications@ikimon.co.jp";
	ALERT_DELIVERY_BATCH_SIZE: "25";
	ALERT_EMAIL_ALLOWED_RECIPIENTS: "yamaki0102@gmail.com";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./publicPresentationEntry");
	}
	interface Env extends __BaseEnv_ShadowGeneratedEnv {}
}
interface ShadowGeneratedEnv extends __BaseEnv_ShadowGeneratedEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ENVIRONMENT" | "PUBLIC_LOCATION_CELL_PRECISION" | "OBSERVATION_DB_NAME" | "OBSERVATION_ARCHIVE_TARGET" | "OBSERVATION_DUAL_WRITE_MODE" | "OBSERVATION_READ_CUTOVER_MODE" | "ZUKAN_FOUNDATION_V2_SHADOW_READ_MODE" | "ZUKAN_FOUNDATION_V2_DUAL_WRITE_MODE" | "ZUKAN_FOUNDATION_V2_WRITE_KILL_SWITCH" | "ZUKAN_FOUNDATION_V2_ALLOWED_TENANTS" | "ZUKAN_FOUNDATION_V2_ALLOWED_OPERATIONS" | "ZUKAN_FOUNDATION_V2_MAX_ENTITIES" | "ALERT_EMAIL_FROM" | "ALERT_DELIVERY_BATCH_SIZE" | "ALERT_EMAIL_ALLOWED_RECIPIENTS">> {}
}
