import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import path from "node:path";
import test from "node:test";

const migrationPath = path.join(process.cwd(), "db", "migrations", "0132_record_observation_foundation.sql");

test("PostgreSQL observation foundation is additive and encodes the observation-first safety contract", () => {
  const sql = readFileSync(migrationPath, "utf8");
  const tables = [
    "record_observations",
    "record_observation_policies",
    "record_observation_source_map",
    "record_observation_media",
    "observation_ai_suggestions",
    "observation_identification_claims",
    "observation_lifecycle_events",
    "occurrence_projection_versions",
    "environment_assessments",
    "environment_assessment_media",
    "record_observation_consistency_ledger",
    "identification_queue_entries",
  ];

  for (const table of tables) {
    assert.match(sql, new RegExp(`CREATE TABLE IF NOT EXISTS\\s+${table}\\b`, "i"), table);
  }

  assert.doesNotMatch(sql, /^\s*(DROP|TRUNCATE|DELETE\s+FROM|UPDATE)\b/im);
  assert.doesNotMatch(sql, /DEFAULT\s+gen_random_uuid\s*\(/i, "IDs must be generated by the application in both runtimes");
  assert.match(sql, /UNIQUE\s*\(record_runtime,\s*record_id,\s*source_key\)/i);
  assert.match(sql, /UNIQUE\s*\(source_runtime,\s*source_entity_kind,\s*source_entity_id,\s*mapping_rule_version\)/i);
  assert.match(sql, /ambiguity_state[\s\S]*'clear'[\s\S]*'needs_review'[\s\S]*'quarantined'/i);
  assert.match(sql, /record_observations_human_promotion_chk[\s\S]*reviewed_by_actor_kind[\s\S]*reviewed_by_actor_id[\s\S]*reviewed_at/i);
  assert.match(sql, /record_observations_data_use_consent_chk[\s\S]*data_use_consent_key/i);
  assert.match(sql, /record_observations_accepted_claim_fk[\s\S]*FOREIGN KEY\s*\(observation_id,\s*accepted_identification_id\)/i);
  assert.match(sql, /occurrence_projection_versions_claim_fk[\s\S]*FOREIGN KEY\s*\(observation_id,\s*accepted_identification_id\)/i);
  assert.match(sql, /ON DELETE RESTRICT/i);
  assert.doesNotMatch(sql, /observation_lifecycle_events[\s\S]{0,300}ON DELETE CASCADE/i);
  assert.match(sql, /confidence_score\s+NUMERIC\(6,5\)[\s\S]*confidence_score\s*>=\s*0[\s\S]*confidence_score\s*<=\s*1/i);
  assert.match(sql, /octet_length\(before_json::text\)\s*<=\s*16384/i);
  assert.match(sql, /octet_length\(provenance_json::text\)\s*<=\s*65536/i);
  assert.match(sql, /consistency_state[\s\S]*'matched'[\s\S]*'mismatched'[\s\S]*'retryable'[\s\S]*'quarantined'/i);
  assert.match(sql, /attempt_count[\s\S]*attempt_count\s*<=\s*100/i);
  assert.match(sql, /accepts_identification_proposals\s+BOOLEAN\s+NOT NULL\s+DEFAULT\s+TRUE/i);
  assert.match(sql, /CREATE UNIQUE INDEX IF NOT EXISTS\s+idx_observation_identification_claims_accepted[\s\S]*WHERE claim_status = 'accepted'/i);
  assert.match(sql, /CREATE UNIQUE INDEX IF NOT EXISTS\s+idx_occurrence_projection_versions_active[\s\S]*WHERE projection_state = 'active'/i);
  assert.match(sql, /CREATE OR REPLACE FUNCTION\s+enforce_occurrence_projection_gate/i);
  assert.match(sql, /COALESCE\(rights_decision_json\s*->>\s*'decision'\s*=\s*'allow',\s*FALSE\)/i);
  assert.doesNotMatch(sql, /ask_the_community|recruit|solicit|募集|みんなに聞く/i);
});
